import { Metadata } from "next";
import { Toaster } from "sonner";

export const metadata: Metadata = {
    title: 'Recupero de contraseña',
    description: 'Generated by create next app',
}


export default function ResetPasswordLayout({ children }: { children: React.ReactNode }) {

    return (
        <section className="min-h-screen bg-background text-foreground relative flex ">
            {children}
            <Toaster className="mx-auto" />
        </section>
    )
}