import { Metadata } from "next";

export const metadata: Metadata = {
    title: 'Publicidades',
    description: 'Generated by create next app',
}

export default async function AdminLayout({ children }: { children: React.ReactNode }) {

    return (
        <section>
            {children}
        </section>
    )
}