import { decodeToken } from "@/utils/utils";
import { Metadata } from "next";
import { Toaster } from "sonner";

export const metadata: Metadata = {
    title: 'Admin Login',
    description: 'Generated by create next app',
}


export default function LoginAdminLayout({ children }: { children: React.ReactNode }) {

    const token = decodeToken();


    return (
        <section className="min-h-screen bg-background text-foreground relative flex ">
            {children}
            <Toaster />
        </section>
    )
}