
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import { ContextProvider } from "@/components/provider/ContextProvider";
import { Toaster } from "sonner";
import NextAuthProviders from "./NextAuthProviders";
import dynamic from "next/dynamic";


const Footer = dynamic(() => import("@/components/footer/Footer"), { ssr: false });

const fontJakarta = Plus_Jakarta_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
  variable: '--font-jakarta'
})

export const metadata: Metadata = {
  title: "Tendencia de noticias",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={cn("min-h-screen bg-background antialiased text-foreground", fontJakarta.className)}>
        <NextAuthProviders>
          <ContextProvider>
            {children}
            <Footer />
          </ContextProvider>
        </NextAuthProviders>
        <Toaster className="mx-auto" />
      </body>
    </html>
  );
}
