import { Metadata } from "next"
import { redirect } from "next/navigation"

export const metadata: Metadata = {
    title: 'Admin Panel',
    description: 'Generated by create next app',
}

async function getUser() {
    try {
        const res = await fetch('http://localhost:3000/api/auth/profile')
        if (res.status === 404) {
            redirect('/');
        }
        return await res.json();
    } catch (error) {
        console.error('Error al obtener el perfil del usuario:', error);
        redirect('/');
    }
}

export default async function layout({ children }: { children: React.ReactNode }) {

    const user = await getUser();

    console.log(user)

    return (
        <section>
            {children}
        </section>
    )
}