import { AdminProfile } from "@/components/dashboard/layout/AdminProfile";
import Sidebar from "@/components/dashboard/layout/Sidebar"
import { decodeToken } from "@/utils/utils";
import { Metadata } from "next"
import { Toaster } from 'sonner'

export const metadata: Metadata = {
    title: 'Admin Panel | Noticias',
    description: 'Generated by create next app',
}


export default function layout({ children }: { children: React.ReactNode }) {

    const token = decodeToken();

    return (
        <section className="min-h-screen bg-background text-foreground relative flex ">
            <Sidebar />
            <div className="flex-1 ml-[200px] overflow-y-auto p-6">
                {children}
            </div>
            <AdminProfile fullname={token?.fullname} email={token?.email} role={token?.role} />
            <Toaster />
        </section>
    )
}